name: "CICD"

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ 'main' ]

jobs:
  lint_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: "Check out the code"
        uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "0.5.13"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Sync dependencies"
        run: uv sync

      - name: "Run linting"
        run: uv run ruff check --fix .

      - name: "Run formatting"
        run: uv run ruff format .

      - name: "Run static type checking"
        run: uv run mypy . --explicit-package-bases

      - name: "Run unit tests"
        run: uv run pytest
